Servo.SetLED(1, false)
music.playMelody("C D E F G A B C5 ", 120)
basic.forever(function () {
    Servo.SetLED(0, false)
    Servo.SetLED(1, false)
    Servo.SetLED(2, false)
    basic.pause(500)
    Servo.SetLED(0, true)
    Servo.SetLED(1, true)
    Servo.SetLED(2, true)
    basic.pause(500)
})